# Site settings
title: Lucas REMOND
email: lucas.remond@hotmail.com
url: https://example.github.io
description: "Welcome to my site. I'm Lucas REMOND and here is my blog where i post my recipes. I hope you are going to like it and don't hesitate to contact me if you have any reports or question about my page ! Thak you"
keywords: "Ambition, Precision, Creativity"
skills: "Pastry guy, Cooking lover, Chemist"
meta_author: Remond Lucas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: REMOND Lucas
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://www.instagram.com/lucasremond/
  - title: facebook
    url: https://www.facebook.com/lucas.remond.3
  - title: Linkedin
    url: https://www.linkedin.com/in/lucas-remond-796886198/
  - title: TalentToday
    url: https://app.talentoday.com/users/lucas-remond/profile/last/myti/personality

# Postal address (add as many lines as necessary)
address:
  - line: 7 rue Victo Hugo
  - line: Lyon FRANCE 69002

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
